#!/bin/sh

. /etc/profile

URL="http://admin@localhost/rest/apps"
PKG="50_havis.device.rf-api.jar 50_@Bundle-SymbolicName@.fragment.jar 50_@Bundle-SymbolicName@.jar 50_havis.net.rest.rf.jar"

for pkg in $PKG; do
  busybox wget $URL/$pkg/plug -q --spider
done

exit 0